# fly.toml app configuration file generated for pixeltest on 2025-05-27T20:42:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pixeltest"
primary_region = "atl"

[build]

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

kill_signal = "SIGTERM"
kill_timeout = 30
